### PR TITLE
Feature: Added ability to disable certain elements to card and card-autoplay shortcodes

### PR DESCRIPTION
**Pull request by DogByteMarketing**
You can now disable the following via an additional attribute:

- Excerpt
- Tags
- Categories

### CODE REVIEW

**Comment by crftwrk** [comment]
Thank you! If we open this box, we should go straight and add this feature to this templates as well:

- sc-swiper-hero-fade.php
- sc-swiper-hero.php

And bS Grid https://github.com/bootscore/bs-grid needs feature in following templates:

- sc-grid.php
- sc-hero.php
- sc-list.php

Are you able to do that?

**Comment by DogByteMarketing** [comment]
> 

We can, but it'll be sometime next week. We just added it on the fly because we been adding it to designs we build for clients and figured it would help some others out by adding it to core.

**Comment by crftwrk** [comment]
Thank you! This is not urgent, take your time. I mean that we can merge when this is completed, create a new release and add features to the docs.

**Comment by DogByteMarketing** [comment]
> Thank you! This is not urgent, take your time. I mean that we can merge when this is completed, create a new release and add features to the docs.

You're welcome. The changes have been submitted.

**Review by crftwrk — APPROVED** [review]
Thank you!

**Comment by DogByteMarketing** [comment]
You're welcome

**Pull request merged**
